### ISSUE TITLE
np.float deprecated in numpy 1.20

### ISSUE THREAD

**Issue by IanTBlack** [OceanOptics/pyACS#2]
np.float float was deprecated in version 1.20. Newer versions of numpy used with pyACS will raise an AttributeError when self.t is created in the acs.py file (line 295).  
![np_float_attr_error](https://github.com/OceanOptics/pyACS/assets/27901961/217a6064-9da9-4b7f-878c-ee87545d91bc)

**Comment by doizuc** [comment]
Fixed in [PR#3](https://github.com/OceanOptics/pyACS/pull/3)
